/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdAccountCreateSubscriptionResponse { 
    /**
     * Subscription ID.
     */
    id?: string;
    /**
     * Base64 encoded key for client to decrypt lead data.
     */
    cryptographic_key?: string;
    /**
     * Lead data encryption algorithm.
     */
    cryptographic_algorithm?: string;
    /**
     * Subscription creation time. Unix timestamp in milliseconds.
     */
    created_time?: number;
}
