/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AdCommonTrackingUrls { 
    impression?: Array<string>;
    click?: Array<string>;
    engagement?: Array<string>;
    buyable_button?: Array<string>;
    audience_verification?: Array<string>;
}
