/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Third-party tracking URLs.<br> JSON object with the format: {\"@see https://developers.pinterest.com/docs/redoc/#section/Tracking-URL-eventTracking event enum\":[URL string array],...}<br> For example: {\"impression\": [\"URL1\", \"URL2\"], \"click\": [\"URL1\", \"URL2\", \"URL3\"]}.<br>Up to three tracking URLs are supported for each event type. Tracking URLs set at the ad group or ad level can override those set at the campaign level. May be null. Pass in an empty object - {} - to remove tracking URLs.<br><br> For more information, see @see https://help.pinterest.com/en/business/article/third-party-and-dynamic-tracking\" Third-party and dynamic tracking.
 */
export interface AdGroupCommonTrackingUrls {
    impression?: Array<string>;
    click?: Array<string>;
    engagement?: Array<string>;
    buyable_button?: Array<string>;
    audience_verification?: Array<string>;
}
