/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchOperationStatus } from './batchOperationStatus';
import { CatalogsType } from './catalogsType';
import { CreativeAssetsProcessingRecord } from './creativeAssetsProcessingRecord';


/**
 * Object describing the catalogs creative assets items batch
 */
export interface CatalogsCreativeAssetsItemsBatch { 
    /**
     * Id of the catalogs items batch
     */
    batch_id?: string;
    /**
     * Time of the batch creation: YYYY-MM-DD\'T\'hh:mm:ssTZD
     */
    readonly created_time?: string;
    /**
     * Time of the batch completion: YYYY-MM-DD\'T\'hh:mm:ssTZD
     */
    readonly completed_time?: string | null;
    status?: BatchOperationStatus;
    catalog_type: CatalogsType;
    /**
     * Array with the catalogs items processing records part of the catalogs items batch
     */
    items?: Array<CreativeAssetsProcessingRecord>;
}
export namespace CatalogsCreativeAssetsItemsBatch {
}
