/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogsLocale } from './catalogsLocale';
import { CatalogsProductGroupFiltersRequest } from './catalogsProductGroupFiltersRequest';
import { CatalogsProductGroupUpdateRequest } from './catalogsProductGroupUpdateRequest';
import { CatalogsVerticalProductGroupUpdateRequest } from './catalogsVerticalProductGroupUpdateRequest';
import { Country } from './country';


/**
 * @type CatalogsProductGroupsUpdateRequest
 * @export
 */
export type CatalogsProductGroupsUpdateRequest = CatalogsProductGroupUpdateRequest | CatalogsVerticalProductGroupUpdateRequest;

