/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogsCreativeAssetsItemsPostFilter } from './catalogsCreativeAssetsItemsPostFilter';
import { CatalogsHotelItemsPostFilter } from './catalogsHotelItemsPostFilter';
import { CatalogsRetailItemsPostFilter } from './catalogsRetailItemsPostFilter';
import { CatalogsType } from './catalogsType';


/**
 * @type CatalogsItemsPostFilters
 * @export
 */
export type CatalogsItemsPostFilters = CatalogsCreativeAssetsItemsPostFilter | CatalogsHotelItemsPostFilter | CatalogsRetailItemsPostFilter;

