/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogsCreativeAssetsBatchItem } from './catalogsCreativeAssetsBatchItem';
import { CatalogsType } from './catalogsType';
import { Country } from './country';
import { Language } from './language';


/**
 * Request object to update catalogs creative assets items
 */
export interface CatalogsCreativeAssetsBatchRequest { 
    catalog_type: CatalogsType;
    country: Country;
    language: Language;
    /**
     * Array with creative assets item operations
     */
    items: Array<CatalogsCreativeAssetsBatchItem>;
    /**
     * Catalog id pertaining to the creative assets item. If not provided, default to oldest creative assets catalog
     */
    catalog_id?: string;
}
export namespace CatalogsCreativeAssetsBatchRequest {
}
