/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CatalogsCreativeAssetsBatchItem } from './catalogsCreativeAssetsBatchItem';
import { CatalogsCreativeAssetsBatchRequest } from './catalogsCreativeAssetsBatchRequest';
import { CatalogsHotelBatchRequest } from './catalogsHotelBatchRequest';
import { CatalogsRetailBatchRequest } from './catalogsRetailBatchRequest';
import { CatalogsType } from './catalogsType';
import { Country } from './country';
import { Language } from './language';


/**
 * A request object that can have multiple operations on a single batch
 */
/**
 * @type CatalogsVerticalBatchRequest
 * A request object that can have multiple operations on a single batch
 * @export
 */
export type CatalogsVerticalBatchRequest = CatalogsCreativeAssetsBatchRequest | CatalogsHotelBatchRequest | CatalogsRetailBatchRequest;

