/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ItemAttributesRequest } from './itemAttributesRequest';


/**
 * An item to be upserted
 */
export interface CatalogsUpsertRetailItem { 
    /**
     * The catalog item id in the merchant namespace
     */
    item_id: string;
    operation: CatalogsUpsertRetailItem.OperationEnum;
    attributes: ItemAttributesRequest;
}
export namespace CatalogsUpsertRetailItem {
    export type OperationEnum = 'CREATE' | 'UPDATE' | 'UPSERT' | 'DELETE';
    export const OperationEnum = {
        Create: 'CREATE' as OperationEnum,
        Update: 'UPDATE' as OperationEnum,
        Upsert: 'UPSERT' as OperationEnum,
        Delete: 'DELETE' as OperationEnum
    }
}
