/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { NonNullableCatalogsCurrency } from './nonNullableCatalogsCurrency';


/**
 * A currency filter. This filter cannot be negated
 */
export interface CatalogsProductGroupCurrencyCriteria { 
    values: NonNullableCatalogsCurrency;
    negated?: boolean;
}
export namespace CatalogsProductGroupCurrencyCriteria {
}
