/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatalogsReportDistributionIssueFilter { 
    report_type: CatalogsReportDistributionIssueFilter.ReportTypeEnum;
    /**
     * Unique identifier of a catalog. If not given, oldest catalog will be used
     */
    catalog_id?: string;
}
export namespace CatalogsReportDistributionIssueFilter {
    export type ReportTypeEnum = 'DISTRIBUTION_ISSUES';
    export const ReportTypeEnum = {
        DistributionIssues: 'DISTRIBUTION_ISSUES' as ReportTypeEnum
    }
}
