/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CatalogsHotelItemsPostFilter { 
    catalog_type: CatalogsHotelItemsPostFilter.CatalogTypeEnum;
    hotel_ids: Array<string>;
    /**
     * Catalog id pertaining to the hotel item. If not provided, default to oldest hotel catalog
     */
    catalog_id?: string;
}
export namespace CatalogsHotelItemsPostFilter {
    export type CatalogTypeEnum = 'HOTEL';
    export const CatalogTypeEnum = {
        Hotel: 'HOTEL' as CatalogTypeEnum
    }
}
