/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ConversionTagConfigs {
    /**
     * Whether Automatic Enhanced Match email is enabled. See @see https://help.pinterest.com/en/business/article/enhanced-match\" Enhanced match for more information.
     */
    aem_enabled?: boolean | null;
    /**
     * Metadata ingestion frequency.
     */
    md_frequency?: number | null;
    /**
     * Whether Automatic Enhanced Match name is enabled. See @see https://help.pinterest.com/en/business/article/enhanced-match\" Enhanced match for more information.
     */
    aem_fnln_enabled?: boolean | null;
    /**
     * Whether Automatic Enhanced Match phone is enabled. See @see https://help.pinterest.com/en/business/article/enhanced-match\" Enhanced match for more information.
     */
    aem_ph_enabled?: boolean | null;
    /**
     * Whether Automatic Enhanced Match gender is enabled. See @see https://help.pinterest.com/en/business/article/enhanced-match\" Enhanced match for more information.
     */
    aem_ge_enabled?: boolean | null;
    /**
     * Whether Automatic Enhanced Match birthdate is enabled. See @see https://help.pinterest.com/en/business/article/enhanced-match\" Enhanced match for more information.
     */
    aem_db_enabled?: boolean | null;
    /**
     * Whether Automatic Enhanced Match location is enabled. See @see https://help.pinterest.com/en/business/article/enhanced-match\" Enhanced match for more information.
     */
    aem_loc_enabled?: boolean | null;
}
