/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerList {
    /**
     * Associated ad account ID.
     */
    ad_account_id?: string;
    /**
     * Creation time. Unix timestamp in seconds.
     */
    created_time?: number;
    /**
     * Customer list ID.
     */
    id?: string;
    /**
     * Customer list name.
     */
    name?: string;
    /**
     * Total number of list updates.  List creation counts as one batch. Each @see /docs/redoc/#operation/ads_v3_customer_list_add_handler_PUTAppend or @see /docs/redoc/#operation/ads_v3_customer_list_remove_handler_PUTRemove API call counts as another. List creation via the Ads Manager UI could result in more than one batch since the UI breaks up large lists.
     */
    num_batches?: number;
    /**
     * Number of removed user records. In a @see /docs/redoc/#operation/ads_v3_customer_list_remove_handler_PUTRemove API call, this counter increases even if the user is not found in the list.
     */
    num_removed_user_records?: number;
    /**
     * Number of uploaded user records. In an @see /docs/redoc/#operation/ads_v3_customer_list_add_handler_PUTAppend API call, this counter increases even if the uploaded user is already in the list.
     */
    num_uploaded_user_records?: number;
    /**
     * Customer list status. TOO_SMALL - the list has less than 100 Pinterest users.
     */
    status?: CustomerList.StatusEnum;
    /**
     * Always \"customerlist\".
     */
    type?: string;
    /**
     * Last update time. Unix timestamp in seconds.
     */
    updated_time?: number;
    /**
     * Customer list errors
     */
    exceptions?: object;
}
export namespace CustomerList {
    export type StatusEnum = 'PROCESSING' | 'READY' | 'TOO_SMALL' | 'UPLOADING';
    export const StatusEnum = {
        Processing: 'PROCESSING' as StatusEnum,
        Ready: 'READY' as StatusEnum,
        TooSmall: 'TOO_SMALL' as StatusEnum,
        Uploading: 'UPLOADING' as StatusEnum
    }
}
