/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Format of generated report
 */
export type DataOutputFormat = 'JSON' | 'CSV';

export const DataOutputFormat = {
    Json: 'JSON' as DataOutputFormat,
    Csv: 'CSV' as DataOutputFormat
}
