/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BaseInviteDataResponse } from './baseInviteDataResponse';
import { DeleteInvitesResultsResponseArrayItemsInnerException } from './deleteInvitesResultsResponseArrayItemsInnerException';


export interface DeleteInvitesResultsResponseArrayItemsInner { 
    exception?: DeleteInvitesResultsResponseArrayItemsInnerException | null;
    invite?: BaseInviteDataResponse | null;
}
