/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * An object containing the permissions a business has on the asset.
 */
export interface GetBusinessAssetsResponse { 
    /**
     * Unique identifier of a business asset.
     */
    asset_id?: string;
    /**
     * Type of asset. Currently we only support AD_ACCOUNT and PROFILE.
     */
    asset_type?: string;
}
