/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IntegrationLog } from './integrationLog';


/**
 * Batch of logs sent from an integration application.
 */
export interface IntegrationLogsRequest { 
    logs: Array<IntegrationLog>;
}
