/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PermissionsWithOwner = 'ADMIN' | 'ANALYST' | 'FINANCE_MANAGER' | 'AUDIENCE_MANAGER' | 'CAMPAIGN_MANAGER' | 'CATALOGS_MANAGER' | 'PROFILE_PUBLISHER' | 'OWNER';

export const PermissionsWithOwner = {
    Admin: 'ADMIN' as PermissionsWithOwner,
    Analyst: 'ANALYST' as PermissionsWithOwner,
    FinanceManager: 'FINANCE_MANAGER' as PermissionsWithOwner,
    AudienceManager: 'AUDIENCE_MANAGER' as PermissionsWithOwner,
    CampaignManager: 'CAMPAIGN_MANAGER' as PermissionsWithOwner,
    CatalogsManager: 'CATALOGS_MANAGER' as PermissionsWithOwner,
    ProfilePublisher: 'PROFILE_PUBLISHER' as PermissionsWithOwner,
    Owner: 'OWNER' as PermissionsWithOwner
}
