/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PinMediaSourceImagesURLItemsInner } from './pinMediaSourceImagesURLItemsInner';


/**
 * Multiple images urls-based media source
 */
export interface PinMediaSourceImagesURL { 
    source_type?: PinMediaSourceImagesURL.SourceTypeEnum;
    /**
     * Array with image objects.
     */
    items: Array<PinMediaSourceImagesURLItemsInner>;
    index?: number;
}
export namespace PinMediaSourceImagesURL {
    export type SourceTypeEnum = 'multiple_image_urls';
    export const SourceTypeEnum = {
        MultipleImageUrls: 'multiple_image_urls' as SourceTypeEnum
    }
}
