/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BusinessMemberAssetsSummaryAdAccountsInner } from './businessMemberAssetsSummaryAdAccountsInner';
import { BusinessMemberAssetsSummaryProfilesInner } from './businessMemberAssetsSummaryProfilesInner';


export interface UserBusinessRoleBindingAssetsSummary { 
    /**
     * List of ad account IDs and respective permission levels.
     */
    ad_accounts?: Array<BusinessMemberAssetsSummaryAdAccountsInner>;
    /**
     * List of profile IDs and respective permission levels.
     */
    profiles?: Array<BusinessMemberAssetsSummaryProfilesInner>;
}
