/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Metadata for the user that created the business relationship.
 */
export interface UserBusinessRoleBindingCreatedByUser { 
    /**
     * Email of the business member/partner.
     */
    email?: string | null;
    /**
     * Unique identifier of the business member/partner.
     */
    id?: string | null;
    /**
     * Username of the business member/partner.
     */
    username?: string | null;
}
