/**
 * Pinterest REST API
 * Pinterest\'s REST API
 *
 * The version of the OpenAPI document: 5.13.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserBusinessRoleBindingAssetsSummary } from './userBusinessRoleBindingAssetsSummary';
import { UserBusinessRoleBindingCreatedByBusiness } from './userBusinessRoleBindingCreatedByBusiness';
import { UserBusinessRoleBindingCreatedByUser } from './userBusinessRoleBindingCreatedByUser';
import { UserBusinessRoleBindingUser } from './userBusinessRoleBindingUser';


export interface UserBusinessRoleBinding { 
    assets_summary?: UserBusinessRoleBindingAssetsSummary | null;
    /**
     * The access level a user has on the business. This can be EMPLOYEE, BIZ_ADMIN, or PARTNER.
     */
    business_roles?: Array<string>;
    created_by_business?: UserBusinessRoleBindingCreatedByBusiness | null;
    created_by_user?: UserBusinessRoleBindingCreatedByUser | null;
    /**
     * The time the business relationship was created. Returned in milliseconds.
     */
    created_time?: number | null;
    /**
     * Unique identifier of the business member/business partner/employer.
     */
    id?: string;
    /**
     * This field is only relevant when business_role=\"PARTNER\". <br>If is_shared_partner=FALSE, the partner can access your business assets. If assets_summary is not empty, the assets listed are your business assets the partner has access to. <br>If is_shared_partner=TRUE, you can access the partner\'s business asset. If assets_summary is not empty, the assets listed are the partner\'s business assets you have access to.
     */
    is_shared_partner?: boolean;
    user?: UserBusinessRoleBindingUser | null;
}
